### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by int-ua** [int-ua/blender-pixelart#1]
- [ ] Outline node group for creatures

**Comment by int-ua** [comment]
* [x] Reduce sun intensity
 * [ ] Add nodes for brightness/contrast and gamma with default values.
